# Generated by Django 3.0.8 on 2020-08-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('small_description', models.CharField(max_length=250)),
                ('technology_used', models.CharField(max_length=250)),
                ('main_image', models.ImageField(default='static/images/test.png', upload_to='project_images')),
                ('large_description', models.TextField()),
                ('carousel_image_1', models.ImageField(default='static/images/test.png', upload_to='project_images')),
                ('carousel_image_2', models.ImageField(default='static/images/test.png', upload_to='project_images')),
                ('carousel_image_3', models.ImageField(default='static/images/test.png', upload_to='project_images')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
